config/routes.rb
Rails.application.routes.draw do
  root to: 'items#index'

  resources :items, only: :show
    # collection do
    #   get "training", to: "items#training"
    # end
  # end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :trainings
end

app/models/training.rb
class Training < ApplicationRecord
  belongs_to :item
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
    @trainings = Training.where(item_id: @item.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.haml
.wrapper
  .top
    .top__title
      Beginner Muscle Training
    .top__main

      .top__main--menu
        筋トレ初心者にオススメの筋トレ動画をリストアップしました。
      .top__main--text
        鍛えたい部位の画像をクリックすると管理人オススメの筋トレ初心者向けの動画が表示されます。
  .center
    .center__text
      鍛えたい部位をクリック
      .grid
        - @items.each do |item|
          .item
            = link_to item_path(item.id) do
              .item__image
                = image_tag item.image, class: "item_image"
            .item__text
              = link_to "#", class: "item-name" do
                = item.name
  .footer
    .footer__text
      ©️Copyright 2020 Beginner Muscle Training

 

app/views/items/show.html.haml
.title
  = "#{@item.name}の初心者向けオススメ動画一覧"
.main
  .grid
    - @trainings.each do |training|
      %iframe{:allow => "accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture", :allowfullscreen => "", :frameborder => "0", :height => "300px", :src => "#{training.url}", :width => "100%"}

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BeginnerMuscleTraining</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>